# Generated by Django 3.2.8 on 2021-11-16 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publish', models.DateField(default=datetime.date.today)),
                ('date_available', models.DateField()),
                ('date_delivery', models.DateField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(choices=[('PR', 'Processing'), ('RC', 'Ready for Custumize'), ('CS', 'Custumized'), ('RD', 'Ready for Distribution'), ('DT', 'Distribution'), ('CP', 'Complete'), ('RJ', 'Rejected')], default='PR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='orderTimelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('selected', models.BooleanField(null=True)),
                ('nth_order', models.IntegerField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertimelocation', related_query_name='ordertimelocation', to='delivery.order')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='timeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('order_timelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_interval', related_query_name='timeinterval', to='delivery.ordertimelocation')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.warehouse')),
            ],
        ),
    ]
