# Generated by Django 3.2.4 on 2021-07-25 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_ordertimelocation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_publish',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
