# Generated by Django 3.2.4 on 2021-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_ordertimelocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertimelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
    ]
