# Generated by Django 3.2.4 on 2021-07-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_ordertimelocation_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertimelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ordertimelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
    ]
