# Generated by Django 3.2.4 on 2021-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='standart_latitude',
            field=models.DecimalField(decimal_places=16, default=10, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='standart_longitude',
            field=models.DecimalField(decimal_places=16, default=10, max_digits=20),
            preserve_default=False,
        ),
    ]
